### ISSUE TITLE
How do we change the sample chunk size?

### ISSUE THREAD

**Issue by jarork** [MrM0bi/convan#1]
Hi there, I'm currently looking for a g729 decoder in Python. I noticed this repo project can only accept the chunk size of 10, however, the g729 stream data I received in our project is 20 bytes for each chunk. How did you get the libg729.so file? does it have source code? I need to modify the chunk size and compile it into .so file

**Comment by MrM0bi** [comment]
Hi Jarork,
Yes, the source code can be found in the Repo of the owner, as linked in the Readme-File under "Dependencies". 
Here's the link: https://github.com/AlexIII/g729a-python
